services:
    app:
        build: .
        ports:
            - "9000:80"
        volumes:
            - .:/var/www/html
        networks:
            - app_network
        mem_limit: "2G"
        cpus: "1"
        environment:
            - VIRTUAL_HOST=localhost

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shopify_app_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network
        mem_limit: "2G"
        cpus: "1"
    
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - app_network

volumes:
    db_data:

networks:
    app_network:
        driver: bridge